### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by lsj1124**
added package and NLKT data for Travis CI

### CODE REVIEW

**Review by ctang1174 — COMMENTED** [review]
is it possible to specify the requirements of the packages to be greater than or equal to a version number? since for example the latest version of nump is 1.20 and not 1.19 like in the requirement file?

**Comment by lsj1124** [comment]
> is it possible to specify the requirements of the packages to be greater than or equal to a version number? since for example the latest version of nump is 1.20 and not 1.19 like in the requirement file?

Yes, I think so. I just use pycharm to automatically generate the requirement file, but if you want me to specify to one version number, I can do that.

**Comment by ctang1174** [comment]
please just make the numpy requirement >= the current version number that you have in your file and I think that will work fine

**Comment by ctang1174** [comment]
ok, looks good, you can go ahead and merge i think? when the travis checks are done

**Pull request merged**
